CXXFLAGS += -std=c++11

clean:
	rm -f *.o *.a *.dylib a.out

libexplore.dylib: src/explore/explore_me.cpp src/explore/explore_me.h
	${CXX} ${CXXFLAGS} -dynamiclib -Wl,-headerpad_max_install_names -fpic -o libexplore.dylib -install_name @executable_path/libexplore.dylib $<

my_fuzz_test: libexplore.dylib
	@echo "Building $@"
	# The FUZZ_TEST_CFLAGS and FUZZ_TEST_LDFLAGS environment variables
	# are set by cifuzz when it executes the build command. Those must
	# be passed to the compiler and linker (compiling and linking is
	# done in a single invocation here, so we pass both to $CXX here).
	${CXX} ${CXXFLAGS} ${FUZZ_TEST_CFLAGS} ${FUZZ_TEST_LDFLAGS} -Wl,-search_paths_first -Wl,-headerpad_max_install_names -o $@ $@.cpp -L. -lexplore

crashing_fuzz_test.o: src/coverage/crashing_fuzz_test.cpp
	${CXX} ${CXXFLAGS} ${FUZZ_TEST_CFLAGS} -c $<

crashing_fuzz_test: crashing_fuzz_test.o
	${CXX} -o $@ crashing_fuzz_test.o ${LDFLAGS} ${FUZZ_TEST_LDFLAGS}
