name: Push Pipeline

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  workflow_dispatch:

jobs:
  linting:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"

      - name: Check file formatting
        run: make fmt/check

      - name: Check go mod tidy
        run: make tidy/check

      - name: Run linting check
        run: make lint

  unit_tests:
    name: unit tests (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"

      - name: Run unit tests
        run: make test/unit
